GET http://localhost:3000/birthdays.json

###
POST http://localhost:3000/birthdays.json
content-type: application/json

{
  "first_name": "Leon",
  "last_name": "Shimizu",
  "day": "20",
  "month": "07",
  "year": "1999"
}

###
GET http://localhost:3000/birthdays/stassie.json